### ISSUE TITLE
Memory Leaks and suggestions 

### ISSUE THREAD

**Issue by Krish-Parekh** [HackOverflow-1-0/HackOverflow-Android#17]
1. I would like to bring to your attention an issue regarding the implementation of view binding inside ```fragments```. It has been observed that the ```instance``` of the binding is not being destroyed in the ```onDestroyView()``` callback, which can lead to ```memory leaks```. For more information, you can refer to the [documentation](https://developer.android.com/topic/libraries/view-binding) on using view binding in fragments.
2. As a suggestion, I would recommend exploring the use of view binding in the [EventAdapter](https://github.com/HackOverflow-1-0/HackOverflow-Android/blob/master/app/src/main/java/com/fin1te/hackoverflow/adapter/EventAdapter.kt) class for ```ViewHolder```.
3. During my recent work with ```viewPager2```, I encountered issues with memory leaks caused by not properly destroying the ```instances``` of the ```TabLayout and the Adapter```. I suggest we review the implementation in the [HomeFragment](https://github.com/HackOverflow-1-0/HackOverflow-Android/blob/master/app/src/main/java/com/fin1te/hackoverflow/ui/HomeFragment.kt) and consider passing the ```viewLifecycleOwner``` to the adapter, which would make it ```lifecycle aware```.
4. Additionally, I would like to suggest the inclusion of tools such as [LeakCanary](https://square.github.io/leakcanary/) and [KtLinter](https://github.com/jlleitschuh/ktlint-gradle) to aid in detecting and preventing memory leaks and ensuring consistency in the codebase.

**Comment by fin1te** [comment]
Hey @Krish-Parekh, thanks a lot for pointing out these suggestions and the issue regarding memory leaks in this app, I hadn't worked much with LeakCanary before or solving memory leaks, I'm checking it out right now and will try solving this issue by the weekend.

Thanks a lot for pointing this out, really appreciated! 😄

**Comment by fin1te** [comment]
Btw, if you'd like to try out something/contribute do lemme know!

**Comment by Krish-Parekh** [comment]
I am happy to take on these issues. For your convenience, would you like me to create a separate branch for each of them or make all the changes in a single branch?

**Comment by fin1te** [comment]
Hey @Krish-Parekh, thanks a lot! 

you can make all changes on the same branch and make the PR directly to master, that'll be fine.
