### ISSUE TITLE
DataBinding and ViewBinding

### ISSUE THREAD

**Issue by Krish-Parekh** [HackOverflow-1-0/HackOverflow-Android#20]
I was going through the code and I checked we have used ```dataBinding``` in this project, is there any specific reason to use ```dataBinding``` over ```viewBinding```?. I read one article which suggested using _viewBinding because dataBinding creates an overhead and increase_ the ```Build Time``` [StackOverFlow](https://stackoverflow.com/questions/58040778/android-difference-between-databinding-and-viewbinding)

**Comment by fin1te** [comment]
Deliberately using `dataBinding` for multiple reasons like 2-way binding, etc. will be using live data, Viewmodels and so on later on in this project, with more fragments and functionalities that'll be implemented in the coming days, I think trading off `viewBinding` for `dataBinding` would be fine as we'll be needing it in this project.

**Comment by fin1te** [comment]
If later on when most of the functionalities of the app are built, let's see then if we can work without `dataBinding` we'll replace it with `viewBinding`. If and when that's the case, we'll reopen this issue.
